# GitHub Compliance Configuration Example
# This file defines the compliance rules for your GitHub organization

version: 1

# Default settings applied to all repositories
defaults:
  # Merge methods configuration
  merge_methods:
    allow_merge_commit: false
    allow_squash_merge: true
    allow_rebase_merge: false

  # Branch protection rules
  branch_protection:
    patterns: ["main", "master", "release/*"]
    enforce_admins: true
    required_reviews:
      dismiss_stale_reviews: true
      required_approving_review_count: 2
      require_code_owner_reviews: true
      require_last_push_approval: false
    required_status_checks:
      auto_discover: true
      contexts: []
      strict: true
    restrictions:
      users: []
      teams: ["maintainers"]
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true
    lock_branch: false
    allow_fork_syncing: false

  # Security settings
  security:
    secret_scanning: "enabled"
    secret_scanning_push_protection: "enabled"
    dependabot_alerts: true
    dependabot_updates: true
    code_scanning_recommended: true

  # Team permissions
  permissions:
    remove_individual_collaborators: true
    teams:
      - team: "admins"
        permission: "admin"
      - team: "developers"
        permission: "write"
    users:
      - user: "release-manager"
        permission: "admin"

  # Archived repository settings
  archived_repos:
    admin_team_only: true

# Override rules for specific repositories (optional)
rules:
  # Private repositories get stricter settings
  - match:
      only_private: true
    apply:
      security:
        secret_scanning_push_protection: "enabled"

  # Public repositories may have different merge methods
  - match:
      only_private: false
    apply:
      merge_methods:
        allow_merge_commit: true
        allow_squash_merge: true

# Compliance checks to run (optional, defaults to all)
checks:
  enabled:
    - "merge-methods"
    - "team-permissions"
    - "branch-protection"
    - "security-scanning"
    - "archived-repos"